[project]
name = "pointcloudcounterfactual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "emd>=0.0.0",
    "h5py>=3.15.1",
    "hydra-core>=1.3.2",
    "numpy>=2.3.5",
    "optuna>=4.6.0",
    "pykeops>=2.3",
    "pyvista>=0.46.4",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "torch>=2.7.0",
    "torcheval>=0.0.7",
    "torchmetrics>=1.0.3",
]

[project.optional-dependencies]
trackers = [
    "tensorboard>=2.20.0",
    "wandb>=0.23.1",
]
finetuning = [
    "optuna>=4.6.0",
]

[tool.uv]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[[tool.uv.index]]
name = "cuda13.0"
url = "https://download.pytorch.org/whl/cu130"
packages = ["torch"]
