[project]
name = "pointcloudcounterfactual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "drytorch[all-trackers]>=0.1.0rc0",
    "h5py>=3.15.1",
    "optuna>=4.6.0",
    "pykeops>=2.3",
    "pyvista>=0.46.4",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torcheval>=0.0.7",
    "torchmetrics>=1.8.2",
]
