study_name:
  w_encoder

n_trials: 300

params:

  w_autoencoder.model.w_encoder.proj_dim:
    suggest: suggest_categorical
    settings:
      choices: [256, 512]


  w_autoencoder.model.w_encoder.n_heads:
    suggest: suggest_categorical
    settings:
      choices: [4, 8, 16]


  w_autoencoder.model.w_encoder.n_transformer_layers:
    suggest: suggest_int
    settings:
      low: 1
      high: 3


  w_autoencoder.model.w_encoder.feedforward_dim:
    suggest: suggest_categorical
    settings:
      choices: [256, 512, 1024]
