study_name:
  decoder


n_trials: 300
n_startup_trials: 15

params:

  autoencoder.model.decoder.sample_dim:
    suggest: suggest_categorical
    settings:
      choices: [8, 16, 32]

  autoencoder.model.decoder.map_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 3
      suggest: suggest_int
      settings:
        low: 8
        high: 256
        log: true

  autoencoder.model.decoder.conv_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 4
      suggest: suggest_int
      settings:
        low: 64
        high: 512
        log: true
