study_name:
  decoder


n_trials: 300
n_startup_trials: 15

params:

  autoencoder.model.decoder.map_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 3
      suggest: suggest_categorical
      settings:
        choices: [8, 16, 32]

  autoencoder.model.decoder.conv_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 3
      suggest: suggest_categorical
      settings:
        choices: [256, 512, 1024]

  autoencoder.model.decoder.proj_dim:
    suggest: suggest_categorical
    settings:
      choices: [ 256, 512 ]

  autoencoder.model.decoder.n_heads:
    suggest: suggest_categorical
    settings:
      choices: [4, 8]

  autoencoder.model.encoder.n_transformer_layers:
    suggest: suggest_int
    settings:
      low: 1
      high: 3

  autoencoder.model.encoder.feedforward_dim:
    suggest: suggest_categorical
    settings:
      choices: [256, 512, 1024]
