study_name:
  encoder

n_trials: 200

params:

  autoencoder.model.encoder.conv_dims:
    suggest: suggest_list
    settings:
      min_length: 1
      max_length: 4
      suggest: suggest_categorical
      settings:
        choices: [64, 128, 256]

  autoencoder.model.encoder.n_neighbors:
    suggest: suggest_int
    settings:
      low: 10
      high: 30
      log: false

  autoencoder.model.encoder.proj_dim:
    suggest: suggest_categorical
    settings:
      choices: [256, 512]

  autoencoder.model.encoder.mlp_dims:
    suggest: suggest_list
    settings:
      min_length: 3
      max_length: 5
      suggest: suggest_categorical
      settings:
        choices: [256, 512, 1024]

  autoencoder.model.encoder.n_heads:
    suggest: suggest_categorical
    settings:
      choices: [ 4, 8 ]
