study_name:
  learn

n_trials: 100

params:
  autoencoder.train.learn.learning_rate:
    suggest: suggest_float
    settings:
      low: 0.5e-04
      high: 0.5e-03

  autoencoder.train.learn.scheduler.warmup_steps:
    suggest: suggest_int
    settings:
      low: 0
      high: 10

  autoencoder.train.learn.opt_settings.weight_decay:
    suggest: suggest_float
    settings:
      low: 1e-05
      high: 1e-03
      log: true
